remote_theme: just-the-docs/just-the-docs

title: Nautical Systems Documentation
description: Documentation for Nautical Systems 7.0

# Enable search
search_enabled: true

# Dark mode
color_scheme: dark

# Heading anchor links appear on hover
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Aux links
aux_links:
  "GitHub":
    - "https://github.com/pamurphy-absconsulting/nautical_systems"

